name: pr-validation
on:
  pull_request:
    branches:
      - develop
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4
      - name: Linting HTML and CSS files
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4
      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"